---
###################
# File:
# playbooks/configureEtcd.yml
#
# Description:
# Installs/configures an etcd cluster corresponding to instructions here:
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md 
#
# Notes 
#
# Author(s):
#   - Ben Watson
# Notes:
#   - TODO: 
###################
- name: PLAY | Configure etcd
  hosts: k8s-controllers
#  gather_facts: false
  vars:
    - tmp_dir: /tmp/etcd
    - ca_dir: /opt/k8s-ca
  tasks:
  
    ###########
    # define/include any "task-level" tasks here
    ###########
    
    - name: FILE | Ensure destination tmp directory exists
      file:
        path: "{{ tmp_dir }}"
        state: directory
        owner: root
        group: root
      become: true
      tags:
        - tmp_dir
    
    - name: UNARCHIVE | download and extract etcd
      unarchive:
        src: "https://github.com/coreos/etcd/releases/download/v3.2.6/etcd-v3.2.6-linux-amd64.tar.gz"
        dest: "{{ tmp_dir }}"
        remote_src: true
      become: true
      tags:
        - dl_etcd
      
    - name: COPY | copy the etcd binaries to a bin directory
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: true
        mode: 0777
      become: true
      with_items:
        - { src: "{{ tmp_dir }}/etcd-v3.2.6-linux-amd64/etcd", dest: /usr/local/bin/etcd }
        - { src: "{{ tmp_dir }}/etcd-v3.2.6-linux-amd64/etcdctl", dest: /usr/local/bin/etcdctl }
      tags:
        - cp_etcd_bin
        
    - name: FILE | Ensure etcd directories exist
      file:
        path: "{{ item.dir }}"
        state: directory
        owner: root
        group: root
      become: true
      tags:
        - etcd_dirs
      with_items:
        - { dir: /etc/etcd }
        - { dir: /var/lib/etcd }
        
    - name: COPY | copy the keys to etcd conf dirs
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: true
#        mode: 0777
      become: true
      with_items:
        - { src: "{{ ca_dir }}/ca.pem", dest: /etc/etcd/ca.pem }
        - { src: "{{ ca_dir }}/kubernetes-key.pem", dest: /etc/etcd/kubernetes-key.pem }
        - { src: "{{ ca_dir }}/kubernetes.pem", dest: /etc/etcd/kubernetes.pem }
      tags:
        - cp_etcd
        
    - name: SHELL | determine internal IP
      shell: 'echo $(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/ip)'
      register: ret_val_ctl_int_ip
      tags:
        - controller_int_ip
        - etcd_svc_def
        
    - debug:
        var: ret_val_ctl_int_ip
        verbosity: 1
      tags:
        - controller_int_ip
        - etcd_svc_def
        
    - set_fact:
        ctl_int_ip: "{{ ret_val_ctl_int_ip.stdout_lines[0] }}"
      tags:
        - controller_int_ip
        - etcd_svc_def
        
    - set_fact:
        gcp_instance_internal_ip_address: "{{ ret_val_ctl_int_ip.stdout_lines[0] }}"
      tags:
        - controller_int_ip
        - etcd_svc_def
        
    - debug:
        var: ctl_int_ip
        verbosity: 1
      tags:
        - controller_int_ip
        - etcd_svc_def
        
    - name: TEMPLATE | Template out the etcd service def
      template:
        src: etcd.service.j2
        dest: /etc/systemd/system/etcd.service
        owner: root
        group: root
      become: true
      tags:
        - etcd_svc
        - etcd_svc_def
        
    - name: SHELL | run daemon-reload to pick up etcd service definition
      shell: systemctl daemon-reload
      become: true
      tags:
        - etcd_svc
        
    - name: SERVICE | Enable and stop the etcd service
      service:
        name: etcd.service
        enabled: yes
        state: stopped
      become: true
      tags:
        - etcd_svc
        
    - name: FILE | Ensure etcd member directory absent before svc restart
      file:
        path: "{{ item.dir }}"
        state: absent
#        owner: root
#        group: root
      become: true
      tags:
        - etcd_dirs
      with_items:
        - { dir: /var/lib/etcd/member/ }
      
    - name: SERVICE | Enable and start the etcd service
      service:
        name: etcd.service
        enabled: yes
        state: started
      become: true
      tags:
        - etcd_svc