---
###################
# File:
# playbooks/configureKubectlRemoteAccess.yml
#
# Description:
# Sets up the CA Authority box according to instructions here:
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/10-configuring-kubectl.md 
#
# Notes 
#
# Author(s):
#   - Ben Watson
# Notes:
#   - TODO: vault the admin password
###################

- name: PLAY | configure Kubectl remote access
  hosts: ansible-controllers
  gather_facts: false
  vars:
    - tmp_dir: /tmp/etcd
    - ca_dir: /opt/k8s-ca
  tasks:
  
    ###########
    # define/include any "task-level" tasks here
    ###########
    
    - name: SHELL | determine static IP of network
      shell: echo $(gcloud compute addresses describe {{ gcp_net_name }} --region $(gcloud config get-value compute/region) --format 'value(address)')
      register: ret_val_gcp_net_static_ip
      tags:
        - kube_api_server_cer
      
    - debug:
        var: ret_val_gcp_net_static_ip
        verbosity: 1
      tags:
        - kube_api_server_cer
        
    - set_fact:
        gcp_net_static_ip: "{{ ret_val_gcp_net_static_ip.stdout_lines[0] }}"
      tags:
        - kube_api_server_cer
        
    - debug:
        var: gcp_net_static_ip
        verbosity: 1
      tags:
        - kube_api_server_cer
        
    - name: SHELL | Generate kube config for authenticating the admin user
      delegate_to: 127.0.0.1
      shell: /usr/local/bin/kubectl {{ item.cmd }}
      args:
        chdir: "{{ ca_dir }}"
#        creates: "{{ ca_dir }}/{{ inventory_hostname }}.kubeconfig.lock"
#      become: true
      with_items:
        - { cmd: "config set-cluster {{ gcp_net_name }} --certificate-authority=ca.pem --embed-certs=true --server=https://{{ gcp_net_static_ip }}:6443" }
        - { cmd: "config set-credentials admin --client-certificate=admin.pem --client-key=admin-key.pem" }
        - { cmd: "config set-context {{ gcp_net_name }} --cluster={{ gcp_net_name }} --user=admin" }
        - { cmd: "config use-context {{ gcp_net_name }}" }
      tags:
        - worker_kube_config
        
    - name: SHELL | Check health of remote cluster
      delegate_to: 127.0.0.1
      shell: /usr/local/bin/kubectl get componentstatuses
      register: ret_val_status
      
    - debug:
        var: ret_val_status
        verbosity: 1
      tags:
        - kube_api_server_cer
        
    - name: SHELL | List nodes of remote cluster
      delegate_to: 127.0.0.1
      shell: /usr/local/bin/kubectl get nodes
      register: ret_val_nodes
      
    - debug:
        var: ret_val_nodes
        verbosity: 1
      tags:
        - kube_api_server_cer