---
###################
# File:
# playbooks/deleteGcpVMs.yml
#
# Description:
# Deletes the VMs that were spun out on GCP 
#
# Notes 
#
# Author(s):
#   - Ben Watson
# Notes:
#   - TODO: vault the admin password
###################
- name: PLAY | Delete GCP 
  hosts: ["gcp-environment:!ansible-controllers"]
  gather_facts: false
#  vars_files:
#    - vars/vault.yml
  tasks:
  
    ###########
    # define/include any "task-level" tasks here
    ###########
    
    
    #~~~~~~~~~~
    # These tasks will be run once per "environment"
    #~~~~~~~~~~
    
    #~~~~~~~~~~
    # These tasks will be run once per VM inside the environment
    #~~~~~~~~~~
    
    - name: GCE | Ensure VMs (instances) are deleted
      gce:
        instance_names: "{{ gcp_instance_name }}"
        zone: "{{ gcp_zone }}"
        state: absent
        service_account_email: "{{ gcp_service_account_email }}"
        credentials_file: "{{ gcp_credentials_file }}"
        project_id: "{{ gcp_project_id }}"
      delegate_to: 127.0.0.1
      tags:
        - gcp_vm
      register: ret_val
        
    - debug:
        var: ret_val
        verbosity: 1
      tags:
        - gcp_vm
        
    - name: LINEINFILE | Update Ansible Controller's /etc/hosts to remote machine aliases
      lineinfile:
        path: /etc/hosts
        regexp: '{{ inventory_hostname }}'
        state: absent
        backrefs: yes
      become: true
      with_items: ret_val.instance_data
      delegate_to: 127.0.0.1
      tags:
        - gcp_vm