---
###################
# File:
# playbooks/kubernetesTheEasyWay.yml
#
# Description:
# Builds a Kubernetes cluster on Google Cloud Platform 
#
# Notes 
#   - this is primarily an "outer playbook" that calls a bunch of other playbooks
#
# Author(s):
#   - Ben Watson
# Notes:
#   - TODO: vault the admin password
###################
- name: PLAY | Deploy k8s cluster to GCP
  hosts: ["gcp-environment:!ansible-controllers"]
  gather_facts: false
  vars_files:
    - vars/vault.yml
  tasks:
  
    ###########
    # define/include any "task-level" tasks here
    ###########
    - name: SHELL | Here we go...
      delegate_to: 127.0.0.1
      shell: echo "hang onto your butts!"
      
###################
# include other plays in the proper order
###################

#ensure virtual infrastructure exists.
- include: provisionGcpEnvironment.yml

#setup/dist certs
- include: configureCaAuthority.yml

#setup etcd cluster
- include: configureEtcd.yml

#
- include: configureKubernetesControllers.yml

#
- include: configureKubernetesFrontendLoadBalancer.yml

#
- include: configureKubernetesWorkers.yml

#
- include: configureKubectlRemoteAccess.yml

#
- include: provisionPodNetRoutes.yml

#
- include: deployDnsClusterAddon.yml

#
- include: smokeTest.yml