---
###################
# File:
# playbooks/provisionPodNetRoutes.yml
#
# Description:
# Sets internal networking routes for Kubernetes PODs
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/11-pod-network-routes.md 
#
# Notes 
#
# Author(s):
#   - Ben Watson
# Notes:
#   - TODO: vault the admin password
###################

- name: PLAY | provision POD network routes
  hosts: k8s-workers
  gather_facts: false
  vars:
    - tmp_dir: /tmp/crio
    - ca_dir: /opt/k8s-ca
  tasks:
  
    ###########
    # define/include any "task-level" tasks here
    ###########
    
    - name: SHELL | determine internal IP
      delegate_to: 127.0.0.1
      shell: echo $(gcloud compute instances describe {{ inventory_hostname }} --format 'value(networkInterfaces[0].networkIP)')
      register: ret_val_gcp_inst_int_ip
      tags:
        - worker_int_ip
        
    - debug:
        var: ret_val_gcp_inst_int_ip
        verbosity: 1
      tags:
        - worker_int_ip
        
    - set_fact:
        gcp_inst_int_ip: "{{ ret_val_gcp_inst_int_ip.stdout_lines[0] }}"
      tags:
        - worker_int_ip
        
    - debug:
        var: gcp_inst_int_ip
        verbosity: 1
      tags:
        - worker_int_ip
        
    - name: SHELL | determine worker POD CIDR from attribute added to VM at create time
      shell: 'echo $(curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/attributes/pod-cidr)'
      register: ret_val_worker_pod_cidr
      tags:
        - worker_cer
        
    - debug:
        var: ret_val_worker_pod_cidr
        verbosity: 1
      tags:
        - worker_cer
        
    - set_fact:
        gcp_worker_pod_cidr: "{{ ret_val_worker_pod_cidr.stdout_lines[0] }}"
      tags:
        - worker_cer
        
    - debug:
        var: gcp_worker_pod_cidr
        verbosity: 1
      tags:
        - worker_cer