---
###################
# File:
# playbooks/provisionPodNetRoutes.yml
#
# Description:
# Sets internal networking routes for Kubernetes PODs
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/11-pod-network-routes.md 
#
# Notes 
#
# Author(s):
#   - Ben Watson
# Notes:
#   - TODO: vault the admin password
###################

- name: PLAY | provision POD network routes
  hosts: k8s-workers
  gather_facts: false
  vars:
    - tmp_dir: /tmp/crio
    - ca_dir: /opt/k8s-ca
  tasks:
  
    ###########
    # define/include any "task-level" tasks here
    ###########
    
    - name: SHELL | determine internal IP
      delegate_to: 127.0.0.1
      shell: echo $(gcloud compute instances describe {{ inventory_hostname }} --format 'value(networkInterfaces[0].networkIP)')
      register: ret_val_gcp_inst_int_ip
      tags:
        - worker_int_ip
        
    - debug:
        var: ret_val_gcp_inst_int_ip
        verbosity: 1
      tags:
        - worker_int_ip
        
    - set_fact:
        gcp_inst_int_ip: "{{ ret_val_gcp_inst_int_ip.stdout_lines[0] }}"
      tags:
        - worker_int_ip
        
    - debug:
        var: gcp_inst_int_ip
        verbosity: 1
      tags:
        - worker_int_ip
        
    - name: SHELL | determine POD CIDR range
      delegate_to: 127.0.0.1
      shell: echo $(gcloud compute instances describe {{ inventory_hostname }} --format 'value(metadata.items[0].value)')
      register: ret_val_gcp_pod_cidr
      tags:
        - worker_int_ip
        
    - debug:
        var: ret_val_gcp_pod_cidr
        verbosity: 1
      tags:
        - worker_int_ip
        
    - set_fact:
        gcp_inst_pod_cidr: "{{ ret_val_gcp_pod_cidr.stdout_lines[0] }}"
      tags:
        - worker_int_ip
        
    - debug:
        var: gcp_inst_pod_cidr
        verbosity: 1
      tags:
        - worker_int_ip