---
###################
# File:
# playbooks/smokeTest.yml
#
# Description:
# Complete a series of tasks to test and verify Kubernetes
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/13-smoke-test.md 
#
# Notes 
#
# Author(s):
#   - Ben Watson
# Notes:
#   - TODO: vault the admin password
###################

- name: PLAY | Kubernetes smoke test | Secret Generation
  hosts: ansible-controllers
  gather_facts: false
  tasks:
  
    ###########
    # define/include any "task-level" tasks here
    ###########
    
    - name: SHELL | create a generic secret
      delegate_to: 127.0.0.1
      shell: /usr/local/bin/kubectl create secret generic k8s-thw --from-literal="mykey=mydata"
      register: ret_val_smoke_secret
      changed_when: '"created" in ret_val_smoke_secret.stdout'
      failed_when: 'ret_val_smoke_secret.rc != 0 and (ret_val_smoke_secret.rc == 1 and "already exists" not in ret_val_smoke_secret.stderr)'
      tags:
        - smoke_secret
      
    - debug:
        var: ret_val_smoke_secret
        verbosity: 1
      tags:
        - smoke_secret
        
- name: PLAY | Kubernetes smoke test | Secret Retrieval
  hosts: k8s-controllers[0]
  gather_facts: false
  tasks:
  
    ###########
    # define/include any "task-level" tasks here
    ###########
    
    - name: SHELL | create a generic secret
      shell: ETCDCTL_API=3 etcdctl get /registry/secrets/default/k8s-thw | hexdump -C
      register: ret_val_smoke_secret_cont
      tags:
        - smoke_secret
      
    - debug:
        var: ret_val_smoke_secret_cont
        verbosity: 1
      tags:
        - smoke_secret
        
- name: PLAY | Kubernetes smoke test | NGinx deployment
  hosts: ansible-controllers
  gather_facts: false
  tasks:
  
    ###########
    # define/include any "task-level" tasks here
    ###########
    
    - name: SHELL | VERIFICATION | create a nginx deployment
      delegate_to: 127.0.0.1
      shell: /usr/local/bin/kubectl run nginx --image=nginx
      register: ret_val_nginx
      changed_when: '"created" in ret_val_nginx.stdout'
      failed_when: 'ret_val_nginx.rc != 0 and (ret_val_nginx.rc == 1 and "already exists" not in ret_val_nginx.stderr)'
      tags:
        - smoke_nginx
      
    - debug:
        var: ret_val_nginx
        verbosity: 1
      tags:
        - smoke_nginx
        
    - name: SHELL | VERIFICATION | list pod created via nginx deployment
      delegate_to: 127.0.0.1
      shell: /usr/local/bin/kubectl get pods -l run=nginx
      register: ret_val_nginx_get
      tags:
        - smoke_nginx
      
    - debug:
        var: ret_val_nginx_get
        verbosity: 1
      tags:
        - smoke_nginx
        
    - name: SHELL | VERIFICATION | retrieve full name of nginx pod
      delegate_to: 127.0.0.1
      shell: /usr/local/bin/kubectl get pods -l run=nginx -o jsonpath="{.items[0].metadata.name}"
      register: ret_val_nginx_get_full
      tags:
        - smoke_nginx
      
    - debug:
        var: ret_val_nginx_get_full
        verbosity: 1
      tags:
        - smoke_nginx
        
    - name: SHELL | VERIFICATION | get nginx pod logs
      delegate_to: 127.0.0.1
      shell: /usr/local/bin/kubectl logs {{ ret_val_nginx_get_full.stdout }}
      register: ret_val_nginx_get_logs
      tags:
        - smoke_nginx
      
    - debug:
        var: ret_val_nginx_get_logs
        verbosity: 1
      tags:
        - smoke_nginx
       
    - name: SHELL | VERIFICATION | execute a command in a container
      delegate_to: 127.0.0.1
      shell: /usr/local/bin/kubectl exec -ti {{ ret_val_nginx_get_full.stdout }} -- nginx -v
      register: ret_val_nginx_get_version
      tags:
        - smoke_nginx
      
    - debug:
        var: ret_val_nginx_get_version
        verbosity: 1
      tags:
        - smoke_nginx