---
###############################################################################
# File: <role_name>/vars/main.yml
#
# Description: define variables for this role
###############################################################################
